// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBS4pxVLB79HveO6cjZeE4m5T3Zszopqo',
    appId: '1:383146690697:web:e45c8d583c7a613ca51e58',
    messagingSenderId: '383146690697',
    projectId: 'uniroom-1376f',
    authDomain: 'uniroom-1376f.firebaseapp.com',
    storageBucket: 'uniroom-1376f.firebasestorage.app',
    measurementId: 'G-R5XCRP6XXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqw9pgNuQX1AjylZFhp5ERGKxiMFGAkQ',
    appId: '1:383146690697:android:82ad041a2045ffd5a51e58',
    messagingSenderId: '383146690697',
    projectId: 'uniroom-1376f',
    storageBucket: 'uniroom-1376f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3eNhl42DlGEBLKs2hGwtL6UzvGbzrclc',
    appId: '1:383146690697:ios:3e58d9fc5062723ba51e58',
    messagingSenderId: '383146690697',
    projectId: 'uniroom-1376f',
    storageBucket: 'uniroom-1376f.firebasestorage.app',
    iosBundleId: 'com.example.uniroomLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3eNhl42DlGEBLKs2hGwtL6UzvGbzrclc',
    appId: '1:383146690697:ios:3e58d9fc5062723ba51e58',
    messagingSenderId: '383146690697',
    projectId: 'uniroom-1376f',
    storageBucket: 'uniroom-1376f.firebasestorage.app',
    iosBundleId: 'com.example.uniroomLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBS4pxVLB79HveO6cjZeE4m5T3Zszopqo',
    appId: '1:383146690697:web:6ca027539f55c053a51e58',
    messagingSenderId: '383146690697',
    projectId: 'uniroom-1376f',
    authDomain: 'uniroom-1376f.firebaseapp.com',
    storageBucket: 'uniroom-1376f.firebasestorage.app',
    measurementId: 'G-4RHC1GK2VM',
  );
}
